/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fai.aulas.urnafai;

import java.awt.BorderLayout;
import java.util.Map;
import java.util.HashMap;
import java.io.File;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rafa-pires
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    
    private static final String[] Cargos = {"PREFEITO", "VEREADOR"};
    private static final int[] num_Digitos_Cargo = {2, 5};
    
    private static final String ARQUIVO_VOTOS = "votos.txt";
    private static final int CHAVE_CIFRA = 3;
    
    private int cargoAtual = 0;
    private StringBuilder numeroDigitado = new StringBuilder();
    private boolean votoBranco = false;
    private boolean conferindoNome = false;
    
    private CandidatoDAO daoPrefeito = new CandidatoDAO();
    private CandidatoDAO daoVereador = new CandidatoDAO();
    private CandidatoDAO[] daoPorCargo;

    /**
     * Creates new form TelaPrincipal
     */
    private Mesario mesarioLogado;
    
    public TelaPrincipal(Mesario mesario) {
        initComponents();
        daoPorCargo = new CandidatoDAO[] {daoPrefeito, daoVereador};
        setSize(1024, 700);           // tamanho FIXO — não depende mais do pack()
        setLocationRelativeTo(null);
        setLocationRelativeTo(null);
        
        this.mesarioLogado = mesario;
        
        txtMesarioNome.setEditable(false);
        txtHoraInicio.setEditable(false);
        txtMatricula.setEditable(false);

        txtMesarioNome.setText(mesario.getNome());
        txtHoraInicio.setText(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
        txtMatricula.setText(mesario.getMatricula());
        
        jTabbedPane1.setEnabledAt(1, false);
        pnlStatusEleitor.setVisible(false);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        
        sessaoAtiva(false);
        
        java.awt.EventQueue.invokeLater(() -> {
            Zeresima aviso = new Zeresima(this, true);
            aviso.setLocationRelativeTo(this);
            aviso.setVisible(true);
        });
    }
    
    private void iniciarCargo(int indice){
        cargoAtual = indice;
        numeroDigitado.setLength(0);
        votoBranco = false;
        conferindoNome = false;
        
        lblVisorCargo.setText(Cargos[cargoAtual]);
        lblVisorNome.setText("");
        lblVisorPartido.setText("");
        lblVisorFoto.setIcon(null);
        lblVisorVice.setText("");
        lblVisorVice.setVisible(false);
        
        atualizarCaixinhas();
    }
    
    private void atualizarCaixinhas(){
        JLabel[] caixinhas = {lblDigito1, lblDigito2, lblDigito3, lblDigito4, lblDigito5};
        int quantidade = num_Digitos_Cargo[cargoAtual];
        
        for (int i = 0; i < caixinhas.length; i++){
            caixinhas[i].setVisible(i < quantidade);
            caixinhas[i].setText("");
        }
        
        for (int i = 0; i < numeroDigitado.length(); i++){
            caixinhas[i].setText(String.valueOf(numeroDigitado.charAt(i)));
        }
    }
    
    private void sessaoAtiva(boolean ativa){
        iniciarSessao.setEnabled(!ativa);
        encerrarSessao.setEnabled(ativa);
        
        txtCpf.setEnabled(ativa);
        txtTitulo.setEnabled(ativa);
        btnLiberarEleitor.setEnabled(ativa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLiberarEleitor = new javax.swing.JButton();
        txtCpf = new javax.swing.JFormattedTextField();
        txtTitulo = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMesarioNome = new javax.swing.JTextField();
        txtHoraInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        iniciarSessao = new javax.swing.JButton();
        encerrarSessao = new javax.swing.JButton();
        pnlStatusEleitor = new javax.swing.JPanel();
        lblStatusEleitor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlUrna = new javax.swing.JPanel();
        pnlVisor = new javax.swing.JPanel();
        lblVisorCargo = new javax.swing.JLabel();
        lblDigito1 = new javax.swing.JLabel();
        lblDigito2 = new javax.swing.JLabel();
        lblDigito3 = new javax.swing.JLabel();
        lblDigito4 = new javax.swing.JLabel();
        lblDigito5 = new javax.swing.JLabel();
        lblVisorNome = new javax.swing.JLabel();
        lblVisorVice = new javax.swing.JLabel();
        lblVisorPartido = new javax.swing.JLabel();
        lblVisorFoto = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnBranco = new javax.swing.JButton();
        btnCorrige = new javax.swing.JButton();
        btnConfirma = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblApuracaoTitulo = new javax.swing.JLabel();
        btnApurar = new javax.swing.JButton();
        scrollApuracao = new javax.swing.JScrollPane();
        pnlApuracaoConteudo = new javax.swing.JPanel();
        btnLimparApuracao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Identificação do Eleitor");

        jLabel5.setText("CPF do eleitor:");

        jLabel6.setText("Titúlo de eleitor:");

        btnLiberarEleitor.setBackground(new java.awt.Color(0, 153, 204));
        btnLiberarEleitor.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnLiberarEleitor.setForeground(new java.awt.Color(255, 255, 255));
        btnLiberarEleitor.setText("Liberar Eleitor");
        btnLiberarEleitor.addActionListener(this::btnLiberarEleitorActionPerformed);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addActionListener(this::txtCpfActionPerformed);

        try {
            txtTitulo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTitulo.addActionListener(this::txtTituloActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLiberarEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(158, 158, 158)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(txtTitulo))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnLiberarEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Mesário:");

        jLabel2.setText("Horário Início:");

        txtMesarioNome.setBorder(null);
        txtMesarioNome.addActionListener(this::txtMesarioNomeActionPerformed);

        txtHoraInicio.setBorder(null);
        txtHoraInicio.addActionListener(this::txtHoraInicioActionPerformed);

        jLabel3.setText("Matrícula:");

        txtMatricula.setBorder(null);
        txtMatricula.addActionListener(this::txtMatriculaActionPerformed);

        iniciarSessao.setBackground(new java.awt.Color(0, 153, 0));
        iniciarSessao.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        iniciarSessao.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSessao.setText("Iniciar Sessão");
        iniciarSessao.addActionListener(this::iniciarSessaoActionPerformed);

        encerrarSessao.setBackground(new java.awt.Color(255, 51, 0));
        encerrarSessao.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        encerrarSessao.setForeground(new java.awt.Color(255, 255, 255));
        encerrarSessao.setText("Encerrar Sessão");
        encerrarSessao.addActionListener(this::encerrarSessaoActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMesarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(txtHoraInicio, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(encerrarSessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iniciarSessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMesarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iniciarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encerrarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStatusEleitor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblStatusEleitor.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblStatusEleitor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlStatusEleitorLayout = new javax.swing.GroupLayout(pnlStatusEleitor);
        pnlStatusEleitor.setLayout(pnlStatusEleitorLayout);
        pnlStatusEleitorLayout.setHorizontalGroup(
            pnlStatusEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusEleitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlStatusEleitorLayout.setVerticalGroup(
            pnlStatusEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusEleitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStatusEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStatusEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mesário", jPanel1);

        pnlUrna.setBackground(new java.awt.Color(221, 209, 193));
        pnlUrna.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlUrna.setRequestFocusEnabled(false);

        pnlVisor.setBackground(new java.awt.Color(255, 255, 255));
        pnlVisor.setRequestFocusEnabled(false);

        lblVisorCargo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblVisorCargo.setText("PREFEITO");

        lblDigito1.setBackground(new java.awt.Color(255, 255, 255));
        lblDigito1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblDigito1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigito1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblDigito2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblDigito2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigito2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblDigito3.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblDigito3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigito3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblDigito4.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblDigito4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigito4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblDigito5.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblDigito5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigito5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblVisorNome.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N

        lblVisorVice.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        lblVisorPartido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        javax.swing.GroupLayout pnlVisorLayout = new javax.swing.GroupLayout(pnlVisor);
        pnlVisor.setLayout(pnlVisorLayout);
        pnlVisorLayout.setHorizontalGroup(
            pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlVisorLayout.createSequentialGroup()
                        .addComponent(lblDigito1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDigito2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDigito3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDigito4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDigito5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVisorCargo)
                    .addComponent(lblVisorPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVisorNome, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(lblVisorVice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(lblVisorFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pnlVisorLayout.setVerticalGroup(
            pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisorLayout.createSequentialGroup()
                .addGroup(pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVisorLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblVisorCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDigito1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigito2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigito3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigito4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigito5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lblVisorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVisorFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(lblVisorVice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblVisorPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel6.setBackground(new java.awt.Color(58, 53, 53));

        btn1.setBackground(new java.awt.Color(0, 0, 0));
        btn1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.addActionListener(this::btn1ActionPerformed);

        btn2.setBackground(new java.awt.Color(0, 0, 0));
        btn2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.addActionListener(this::btn2ActionPerformed);

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.addActionListener(this::btn3ActionPerformed);

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        btn4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.addActionListener(this::btn4ActionPerformed);

        btn5.setBackground(new java.awt.Color(0, 0, 0));
        btn5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.addActionListener(this::btn5ActionPerformed);

        btn6.setBackground(new java.awt.Color(0, 0, 0));
        btn6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.addActionListener(this::btn6ActionPerformed);

        btn7.setBackground(new java.awt.Color(0, 0, 0));
        btn7.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(this::btn7ActionPerformed);

        btn8.setBackground(new java.awt.Color(0, 0, 0));
        btn8.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(this::btn8ActionPerformed);

        btn9.setBackground(new java.awt.Color(0, 0, 0));
        btn9.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(this::btn9ActionPerformed);

        btn0.setBackground(new java.awt.Color(0, 0, 0));
        btn0.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(this::btn0ActionPerformed);

        btnBranco.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        btnBranco.setText("BRANCO");
        btnBranco.addActionListener(this::btnBrancoActionPerformed);

        btnCorrige.setBackground(new java.awt.Color(255, 102, 0));
        btnCorrige.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        btnCorrige.setText("CORRIGE");
        btnCorrige.addActionListener(this::btnCorrigeActionPerformed);

        btnConfirma.setBackground(new java.awt.Color(51, 153, 0));
        btnConfirma.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        btnConfirma.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirma.setText("CONFIRMA");
        btnConfirma.addActionListener(this::btnConfirmaActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBranco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCorrige)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirma))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout pnlUrnaLayout = new javax.swing.GroupLayout(pnlUrna);
        pnlUrna.setLayout(pnlUrnaLayout);
        pnlUrnaLayout.setHorizontalGroup(
            pnlUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUrnaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(pnlVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        pnlUrnaLayout.setVerticalGroup(
            pnlUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUrnaLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(pnlUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUrna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlUrna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Urna", jPanel2);

        lblApuracaoTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblApuracaoTitulo.setText("Apuração de Votos");

        btnApurar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnApurar.setText("Apurar Votos");
        btnApurar.addActionListener(this::btnApurarActionPerformed);

        pnlApuracaoConteudo.setLayout(new javax.swing.BoxLayout(pnlApuracaoConteudo, javax.swing.BoxLayout.Y_AXIS));
        scrollApuracao.setViewportView(pnlApuracaoConteudo);

        btnLimparApuracao.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnLimparApuracao.setText("Limpar Apuração");
        btnLimparApuracao.addActionListener(this::btnLimparApuracaoActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblApuracaoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                        .addComponent(btnApurar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnLimparApuracao))
                    .addComponent(scrollApuracao))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApuracaoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparApuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApurar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollApuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Apuração", jPanel3);

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configurações");

        jMenu4.setText("jMenu4");
        jMenu2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ajuda");

        jMenu6.setText("jMenu6");
        jMenu5.add(jMenu6);

        jMenuItem3.setText("jMenuItem3");
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed
    private Eleitor eleitorAtual;
    private EleitorDAO eleitorDAO = new EleitorDAO();
    private void btnLiberarEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarEleitorActionPerformed
        // TODO add your handling code here:
        String cpf = txtCpf.getText().trim();
        String titulo = txtTitulo.getText().trim().replaceAll("[^0-9]", "");

        Eleitor eleitor = eleitorDAO.buscaPorCpf(cpf);
        
        if(eleitor == null){
            exibirStatusEleitor(false, "CPF não cadastrado. Verifique o documento apresentado pelo eleitor");
        } else if(!eleitor.getTitulo().equals(titulo)){
            exibirStatusEleitor(false, "Título de eleitor não confere com o CPF informado");
        } else if(eleitor.isJaVotou()){
            exibirStatusEleitor(false, "Este eleitor ja registrou o voto nesta sessão");
        } else {
            exibirStatusEleitor(true, "Eleitor identificado com Sucesso. Urna liberada para votar");
            eleitorAtual = eleitor;
            jTabbedPane1.setEnabledAt(1, true);
            iniciarCargo(0);
        }
    }//GEN-LAST:event_btnLiberarEleitorActionPerformed

    private void txtMesarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesarioNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesarioNomeActionPerformed

    private void txtHoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraInicioActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void iniciarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSessaoActionPerformed
        // TODO add your handling code here:
        txtMesarioNome.setText(mesarioLogado.getNome());
        txtMatricula.setText(mesarioLogado.getMatricula());
        txtHoraInicio.setText(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
        
        sessaoAtiva(true);
    }//GEN-LAST:event_iniciarSessaoActionPerformed

    private void encerrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarSessaoActionPerformed
        // TODO add your handling code here:
        eleitorDAO.resetarVotos();
        
        txtCpf.setText("");
        txtTitulo.setText("");
        pnlStatusEleitor.setVisible(false);
        jTabbedPane1.setEnabledAt(1, false);
        
        JOptionPane.showMessageDialog(this,
            "Sessão encerrada às " + LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")) + ".",
            "Sessão encerrada", JOptionPane.INFORMATION_MESSAGE);
        
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_encerrarSessaoActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void digitarNumero(String digito){
        if(conferindoNome){
            return;
        }
        
        int limite = num_Digitos_Cargo[cargoAtual];
        if(votoBranco || numeroDigitado.length() >= limite){
            return;
        }
        
        numeroDigitado.append(digito);
        atualizarCaixinhas();
    }
    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        digitarNumero("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        digitarNumero("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        digitarNumero("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        digitarNumero("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        digitarNumero("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        digitarNumero("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        digitarNumero("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        digitarNumero("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        digitarNumero("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        digitarNumero("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrancoActionPerformed
        // TODO add your handling code here:
        if(conferindoNome){
            return;
        }
        
        votoBranco = true;
        numeroDigitado.setLength(0);
        JLabel[] caixinhas = {lblDigito1, lblDigito2, lblDigito3, lblDigito4, lblDigito5};
        
        int quantidade = num_Digitos_Cargo[cargoAtual];
        for(int i = 0; i < quantidade; i++){
            caixinhas[i].setText("B");
        }
        
        lblVisorNome.setText("VOTO EM BRANCO");
        lblVisorPartido.setText("");
        lblVisorFoto.setIcon(null);
        lblVisorVice.setVisible(false);
        conferindoNome = true;
    }//GEN-LAST:event_btnBrancoActionPerformed

    private void btnCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrigeActionPerformed
        // TODO add your handling code here:
        numeroDigitado.setLength(0);
        votoBranco = false;
        conferindoNome = false;
        
        lblVisorNome.setText("");
        lblVisorPartido.setText("");
        lblVisorFoto.setIcon(null);
        lblVisorVice.setText("");
        lblVisorVice.setVisible(false);
        
        atualizarCaixinhas();
    }//GEN-LAST:event_btnCorrigeActionPerformed

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        // TODO add your handling code here:
        int limite = num_Digitos_Cargo[cargoAtual];
        
        if(!conferindoNome){
            if(!votoBranco && numeroDigitado.length() < limite){
               JOptionPane.showMessageDialog(this,
                    "Digite os " + limite + " dígitos do número antes de confirmar",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
               return;
            }
            
            exibirNomeCandidato();
            conferindoNome = true;
        } else {
            registrarVoto(Cargos[cargoAtual], votoBranco ? "BRANCO" : numeroDigitado.toString());
            
            if(cargoAtual < Cargos.length - 1){
                iniciarCargo(cargoAtual + 1);
            } else {
                finalizarVotacao();
            }
        }
    }//GEN-LAST:event_btnConfirmaActionPerformed

    private void btnApurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApurarActionPerformed
        // TODO add your handling code here:
        carregarApuracao();
        btnLimparApuracao.setEnabled(true);
    }//GEN-LAST:event_btnApurarActionPerformed

    private void btnLimparApuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparApuracaoActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(this,
            "Isso vai apagar a apuração da tela e excluir o arquivo votos.txt.\n"
            + "Essa ação não pode ser desfeita. Deseja continuar?",
            "Limpar Apuração", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

    if (opcao != JOptionPane.YES_OPTION) {
        return;
    }

    pnlApuracaoConteudo.removeAll();
    pnlApuracaoConteudo.revalidate();
    pnlApuracaoConteudo.repaint();

    File arquivo = new File(ARQUIVO_VOTOS);
    if (arquivo.exists()) {
        arquivo.delete();
    }

    btnLimparApuracao.setEnabled(false);
    }//GEN-LAST:event_btnLimparApuracaoActionPerformed
    
    private void exibirNomeCandidato(){
        Candidato candidato = daoPorCargo[cargoAtual].buscaPorNumero(numeroDigitado.toString());
    
        if(candidato != null){
            lblVisorNome.setText(candidato.getNome());
            lblVisorPartido.setText("Partido: " + candidato.getPartido());
            carregarFotoCandidato(numeroDigitado.toString());
            if(candidato.temVice()){
                lblVisorVice.setText("Vice: " + candidato.getVice());
                lblVisorVice.setVisible(true);
            } else {
                lblVisorVice.setVisible(false);
            }
        } else {
            lblVisorNome.setText("VOTO NULO");
            lblVisorPartido.setText("");
            lblVisorFoto.setIcon(null);
            lblVisorVice.setVisible(false);
        }
    }
    
    private void carregarFotoCandidato(String numero) {
        String caminho = "src/main/java/fai/aulas/urnafai/fotos/" + numero + ".png";
        java.io.File arquivo = new java.io.File(caminho);

        if (arquivo.exists()) {
            ImageIcon icone = new ImageIcon(arquivo.getAbsolutePath());
            Image imagem = icone.getImage().getScaledInstance(
                    lblVisorFoto.getWidth(), lblVisorFoto.getHeight(), Image.SCALE_SMOOTH);
            lblVisorFoto.setIcon(new ImageIcon(imagem));
        } else {
            lblVisorFoto.setIcon(null);
        }
    }
    
    private void registrarVoto(String cargo, String valor){
        String valorCifrado = cifrarCesar(valor, CHAVE_CIFRA);

        try (java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter(ARQUIVO_VOTOS, true))){
            bw.write(cargo + ";" + valorCifrado);
            bw.newLine();
        } catch(java.io.IOException e){
            e.printStackTrace();
        }
    }
    
    private String cifrarCesar(String texto, int chave){
        StringBuilder sb = new StringBuilder();

        for(char c : texto.toCharArray()){
            if(Character.isDigit(c)){
                int novoDigito = (Character.getNumericValue(c) + chave) % 10;
                sb.append(novoDigito);
            } else if(Character.isUpperCase(c)){
                char novaLetra = (char) ('A' + (c - 'A' + chave) % 26);
                sb.append(novaLetra);
            } else {
                sb.append(c);
            }
        }

        return sb.toString();
    }
    
    private String decifrarCesar(String texto, int chave){
        StringBuilder sb = new StringBuilder();
        for(char c : texto.toCharArray()){
            if(Character.isDigit(c)){
                int digito = Character.getNumericValue(c);
                int original = ((digito - chave) % 10 + 10) % 10;
                sb.append(original);
            } else if(Character.isUpperCase(c)){
                int letra = c - 'A';
                int original = ((letra - chave) % 26 + 26) % 26;
                sb.append((char) ('A' + original));
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }
    
    private Map<String, Integer> contarVotos(String cargo){
        Map<String, Integer> contagem = new HashMap<>();
        File arquivo = new File(ARQUIVO_VOTOS);
        if(!arquivo.exists()){
            return contagem;
        }
        
        try (BufferedReader br = new BufferedReader(new FileReader(arquivo))){
            String linha;
            while ((linha = br.readLine()) != null){
                String[] partes = linha.split(";", -1);
                if(partes.length == 2 && partes[0].equals(cargo)){
                    String valor = decifrarCesar(partes[1], CHAVE_CIFRA);
                    contagem.merge(valor, 1, Integer::sum);
                }
            }
        } catch(IOException e){
            e.printStackTrace();
        }
        return contagem;
    }
    
    private void montarSecaoApuracao(String cargo, int indiceCargo, JPanel destino){
       JLabel lblTitulo = new JLabel(cargo);
       lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 16));
       lblTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);
       lblTitulo.setBorder(BorderFactory.createEmptyBorder(0,0,10,0));
       destino.add(lblTitulo);
       
       Map<String, Integer> contagem = contarVotos(cargo);
       int total = 0;
       for(int v : contagem.values()){
           total += v;
       }
       
       List<Candidato> candidatos = new ArrayList<>();
       for (Candidato c : daoPorCargo[indiceCargo].listarTodos()) {
           if (cargo.equals(c.getCargo())) {
               candidatos.add(c);
           }
       }
            
       List<Object[]> linhas = new ArrayList<>();
       
       for(Candidato c : candidatos){
           int votos = contagem.getOrDefault(c.getNumero(), 0);
           linhas.add(new Object[]{c.getNome() + "(" + c.getNumero() + ")", votos});
       }
       
       int votosNulos = 0;
       for(Map.Entry<String, Integer> entry: contagem.entrySet()){
           String chave = entry.getKey();
           if(chave.equals("BRANCO")){
               continue;
           }
           boolean encontrado = false;
           for(Candidato c : candidatos){
               if(c.getNumero().equals(chave)){
                   encontrado = true;
                   break;
               }
           }
           if(!encontrado){
               votosNulos += entry.getValue();
           }
       }
       
       linhas.add(new Object[]{"Votos em Branco", contagem.getOrDefault("BRANCO", 0)});
       linhas.add(new Object[]{"Votos Nulos", votosNulos});
       
       linhas.sort((a,b) -> (Integer) b[1] - (Integer) a[1]);
       
       for(Object[] linha : linhas){
           String nome = (String) linha[0];
           int votos = (Integer) linha[1];
           double percentual = total == 0 ? 0 : (votos * 100.0 / total);
           destino.add(criarLinhaApuracao(nome, votos, percentual));
           destino.add(Box.createVerticalStrut(8));
       }
    }
    
    private JPanel criarLinhaApuracao(String nome, int votos, double percentual) {
        JPanel linha = new JPanel(new BorderLayout(10, 4));
        linha.setBackground(Color.WHITE);
        linha.setBorder(BorderFactory.createEmptyBorder(6, 10, 6, 10));
        linha.setMaximumSize(new Dimension(Integer.MAX_VALUE, 60));
        linha.setAlignmentX(Component.LEFT_ALIGNMENT);

        JLabel lblNome = new JLabel(nome);
        lblNome.setFont(new Font("Segoe UI", Font.BOLD, 13));

        JLabel lblVotos = new JLabel(
                votos + " votos (" + String.format("%.1f", percentual) + "%)");
        lblVotos.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblVotos.setForeground(new Color(80, 80, 80));
        JPanel topo = new JPanel(new BorderLayout());
        topo.setOpaque(false);
        topo.add(lblNome, BorderLayout.WEST);
        topo.add(lblVotos, BorderLayout.EAST);

        JPanel barraFundo = new JPanel(null);
        barraFundo.setBackground(new Color(224, 224, 224));
        barraFundo.setPreferredSize(new Dimension(400, 14));

        JPanel barraPreenchida = new JPanel();
        barraPreenchida.setBackground(new Color(63, 127, 191));
        int largura = (int) (400 * (percentual / 100.0));
        barraPreenchida.setBounds(0, 0, largura, 14);
        barraFundo.add(barraPreenchida);

        linha.add(topo, BorderLayout.NORTH);
        linha.add(barraFundo, BorderLayout.CENTER);

        return linha;
    }
    
    private Font newFont(String segoe_UI, int BOLD, int i) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    private void carregarApuracao() {
        pnlApuracaoConteudo.removeAll();

        montarSecaoApuracao("PREFEITO", 0, pnlApuracaoConteudo);
        pnlApuracaoConteudo.add(Box.createVerticalStrut(24));
        montarSecaoApuracao("VEREADOR", 1, pnlApuracaoConteudo);

        pnlApuracaoConteudo.revalidate();
        pnlApuracaoConteudo.repaint();
    }
    
    private void finalizarVotacao(){
        
        if(eleitorAtual != null){
            eleitorDAO.registrarVoto(eleitorAtual);
            eleitorAtual = null;
        }

        txtCpf.setText("");
        txtTitulo.setText("");
        pnlStatusEleitor.setVisible(false);
        
        JOptionPane.showMessageDialog(this,
                "Votos confirmados com Sucesso\n\nPrefeito e Vereador registrados",
                "Votação concluída", JOptionPane.INFORMATION_MESSAGE);
        
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setSelectedIndex(0);
    }
    
    private void exibirStatusEleitor(boolean autorizado, String mensagem) {
        pnlStatusEleitor.setVisible(true);
        lblStatusEleitor.setText(mensagem);
        if (autorizado) {
            pnlStatusEleitor.setBackground(new Color(230, 244, 234));
            lblStatusEleitor.setForeground(new Color(30, 107, 50));
        } else {
            pnlStatusEleitor.setBackground(new Color(253, 235, 235));
            lblStatusEleitor.setForeground(new Color(178, 34, 34));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));*/
        java.awt.EventQueue.invokeLater(()-> {
            TelaLogin login = new TelaLogin(null, true);
            login.setVisible(true);
            
            Mesario mesario = login.getMesarioAutenticado();
            
            if(mesario != null){
                new TelaPrincipal(mesario).setVisible(true);
            } else {
                System.exit(0);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnApurar;
    private javax.swing.JButton btnBranco;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnCorrige;
    private javax.swing.JButton btnLiberarEleitor;
    private javax.swing.JButton btnLimparApuracao;
    private javax.swing.JButton encerrarSessao;
    private javax.swing.JButton iniciarSessao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblApuracaoTitulo;
    private javax.swing.JLabel lblDigito1;
    private javax.swing.JLabel lblDigito2;
    private javax.swing.JLabel lblDigito3;
    private javax.swing.JLabel lblDigito4;
    private javax.swing.JLabel lblDigito5;
    private javax.swing.JLabel lblStatusEleitor;
    private javax.swing.JLabel lblVisorCargo;
    private javax.swing.JLabel lblVisorFoto;
    private javax.swing.JLabel lblVisorNome;
    private javax.swing.JLabel lblVisorPartido;
    private javax.swing.JLabel lblVisorVice;
    private javax.swing.JPanel pnlApuracaoConteudo;
    private javax.swing.JPanel pnlStatusEleitor;
    private javax.swing.JPanel pnlUrna;
    private javax.swing.JPanel pnlVisor;
    private javax.swing.JScrollPane scrollApuracao;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMesarioNome;
    private javax.swing.JFormattedTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}