/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package fai.aulas.urnafai;

import javax.swing.JOptionPane;

/**
 *
 * @author rafa-pires
 */
public class TelaCadastroCandidato extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroCandidato.class.getName());

    /**
     * Creates new form TelaCadastroCandidato
     */
    public TelaCadastroCandidato(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtVice.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPartido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cPrefeitoVereador = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtVice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnSelecionarFoto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblFotoSelecionada = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Candidato");

        jLabel2.setText("Número:");

        txtNumero.addActionListener(this::txtNumeroActionPerformed);

        txtNome.addActionListener(this::txtNomeActionPerformed);

        jLabel3.setText("Nome:");

        txtPartido.addActionListener(this::txtPartidoActionPerformed);

        jLabel4.setText("Partido:");

        cPrefeitoVereador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "PREFEITO", "VEREADOR" }));
        cPrefeitoVereador.addActionListener(this::cPrefeitoVereadorActionPerformed);

        jLabel5.setText("Cargo:");

        txtVice.addActionListener(this::txtViceActionPerformed);

        jLabel6.setText("Vice:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        btnSelecionarFoto.setText("Adicionar Foto");
        btnSelecionarFoto.addActionListener(this::btnSelecionarFotoActionPerformed);

        jLabel7.setText("Foto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel5))
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel7))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSelecionarFoto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(lblFotoSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNome)
                                        .addComponent(txtPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cPrefeitoVereador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtVice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPrefeitoVereador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionarFoto)
                    .addComponent(jLabel7)
                    .addComponent(lblFotoSelecionada)
                    .addComponent(jLabel8))
                .addGap(62, 62, 62)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartidoActionPerformed

    private void cPrefeitoVereadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPrefeitoVereadorActionPerformed
        // TODO add your handling code here:
        String cargo = (String) cPrefeitoVereador.getSelectedItem();
        
        if("PREFEITO".equals(cargo)){
            txtVice.setEnabled(true);
        } else {
            txtVice.setEnabled(false);
            txtVice.setText("");
        }
    }//GEN-LAST:event_cPrefeitoVereadorActionPerformed

    private void txtViceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViceActionPerformed

    private CandidatoDAO candidatoDAO = new CandidatoDAO();
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String cargo = (String) cPrefeitoVereador.getSelectedItem();
    
        if("...".equals(cargo)){
            JOptionPane.showMessageDialog(this,
                "Selecione um Cargo",
                "Cadastro de Candidato",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String numero = txtNumero.getText().trim();
        
        if("PREFEITO".equals(cargo) && numero.length() != 2){
            JOptionPane.showMessageDialog(this,
                    "Número de prefeito deve conter 2 dígitos",
                    "Cadastro de Candidadto",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if("VEREADOR".equals(cargo) && numero.length() != 5){
            JOptionPane.showMessageDialog(this,
                    "Número de vereador deve conter 5 dígitos",
                    "Cadastro de Candidato",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(candidatoDAO.numeroExiste(numero)){
            JOptionPane.showMessageDialog(this,
                    "Número de candidato já existente",
                    "Cadastro de Candidato",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String nome = txtNome.getText().trim();
        String partido = txtPartido.getText().trim();
        String vice = "PREFEITO".equals(cargo) ? txtVice.getText().trim() : null;
        
        candidatoDAO.cadastrarCandidato(numero, nome, partido, vice, cargo);
        
        if(fotoSelecionada != null){
            salvarFoto(numero);
        }
        
        JOptionPane.showMessageDialog(this,
            "Cadastro concluído com sucesso",
            "Cadastro de Eleitor",
        JOptionPane.INFORMATION_MESSAGE);
        
        limpaCampo();
    }//GEN-LAST:event_btnCadastrarActionPerformed
    
    private void salvarFoto(String numero){
        try {
            java.io.File pasta = new java.io.File("src/main/java/fai/aulas/urnafai/fotos");
            if(!pasta.exists()){
                pasta.mkdirs();
            }

            java.io.File destino = new java.io.File(pasta, numero + ".png");
            java.nio.file.Files.copy(fotoSelecionada.toPath(), destino.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        } catch (java.io.IOException e){
            e.printStackTrace();
        }
    }
    
    private java.io.File fotoSelecionada;
    private void btnSelecionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarFotoActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imagens (PNG)", "png"));
        int resultado = chooser.showOpenDialog(this);

        if(resultado == javax.swing.JFileChooser.APPROVE_OPTION){
            fotoSelecionada = chooser.getSelectedFile();
            lblFotoSelecionada.setText(fotoSelecionada.getName());
        }
    }//GEN-LAST:event_btnSelecionarFotoActionPerformed

    public void limpaCampo(){
        txtNumero.setText("");
        txtNome.setText("");
        txtPartido.setText("");
        cPrefeitoVereador.setSelectedIndex(0);
        txtVice.setText("");
        txtVice.setEnabled(false);
        fotoSelecionada = null;
        lblFotoSelecionada.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaCadastroCandidato dialog = new TelaCadastroCandidato(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSelecionarFoto;
    private javax.swing.JComboBox<String> cPrefeitoVereador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFotoSelecionada;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPartido;
    private javax.swing.JTextField txtVice;
    // End of variables declaration//GEN-END:variables
}